name: smoge
version: 0.1.0.0
github: "ArcSecant/smoge"
license: BSD3
author: "ArcSecant"
copyright: "2021 ArcSecant"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/smoge#readme>

dependencies:
  - base
  - servant
  - servant-server
  - servant-client
  - http-client
  - http-client-tls
  - transformers
  - aeson
  - wai
  - warp
  - warp-tls

library:
  source-dirs: backend/src

executables:
  smoge-exe:
    main: Main.hs
    source-dirs: backend/app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - smoge

tests:
  smoge-test:
    main: Spec.hs
    source-dirs: backend/test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - smoge